default: run

build_dir := "build"

build:
    mkdir -p {{build_dir}}

    cargo run -- vec2.saya -o {{build_dir}}/vec2.ssa -t {{build_dir}}/vec2.td -N vec2
    cargo run -- random.saya -o {{build_dir}}/random.ssa -t {{build_dir}}/random.td -N random
    cargo run -- main.saya -o {{build_dir}}/main.ssa -M vec2={{build_dir}}/vec2.td -M random={{build_dir}}/random.td

    qbe {{build_dir}}/vec2.ssa -o {{build_dir}}/vec2.s
    qbe {{build_dir}}/random.ssa -o {{build_dir}}/random.s
    qbe {{build_dir}}/main.ssa -o {{build_dir}}/main.s

    cc -c {{build_dir}}/vec2.s -o {{build_dir}}/vec2.o
    cc -c {{build_dir}}/random.s -o {{build_dir}}/random.o
    cc -c {{build_dir}}/main.s -o {{build_dir}}/main.o

    cc {{build_dir}}/vec2.o {{build_dir}}/random.o {{build_dir}}/main.o -lc -o {{build_dir}}/main

run: build
    ./{{build_dir}}/main

clean:
    rm -rf {{build_dir}}
